export const USER_UNIVERSITY_VERIFICATION = 'VERIFICATION';
export const USER_UNIVERSITY_NO_VERIFICATION = 'NO_VERIFICATION';
export const USER_UNIVERSITY_VERIFYING = 'VERIFYING';
export const USER_UNIVERSITY_HOLDING_VERIFICATION = 'HOLDING_VERIFICATION';

export const USER_STATUS_ACTIVE = 'ACTIVE';
export const USER_STATUS_INACTIVE = 'INACTIVE';
export const USER_STATUS_DRAW = 'DRAW';
